### ISSUE TITLE
Document Monolog Handler for the new PHP SDK

### ISSUE THREAD

**Issue by B-Galati** [getsentry/sentry-docs#1104]
If I am not mistaken I cannot find anything on the monolog handler for the new SDK.

Let me know if I am wrong.

**Comment by ninze** [comment]
This is even more relevant now that Monolog has removed `RavenHandler` from their repo in favor of using `Sentry\Monolog\Handler`. I ended up with the following code, no idea if it is the correct or recommended way to use Sentry.

	$options = [
		'dsn' => ___DSN___,
		'default_integrations' => false, // use Monolog to send errors instead of using Raven's built in reporter
	];

	$client = \Sentry\ClientBuilder::create($options)->getClient();
	$hub = new \Sentry\State\Hub($client);
	$handler = new \Sentry\Monolog\Handler($hub, \Monolog\Logger::ERROR);

**Comment by ste93cry** [comment]
The code above is _almost_ fine, however it's missing some critical parts that would setup the environment correctly (e.g. binding of the client to the current hub). A more simplified code can looks like this (untested, I wrote it on the fly):

```php
use Monolog\Logger as Logger;
use Sentry\Monolog\Handler as MonologHandler;
use Sentry\State\HubAdapter;

\Sentry\init([
    'dsn' => '___DSN___',
    'default_integrations' => false,
    'integrations' => [
        ... // Actually you must add back all default integrations except for the ones that do the error handling
    ],
]);

$handler = new MonologHandler(HubAdapter::getInstance(), Logger::ERROR);
```

Note that using the `init` function the client is automatically created and attached to an hub that is set as the current hub. Failing to do it means that some integrations may not work correctly as they try to get the current hub which may be different from the one used by the Monolog handler or may be missing at all, thus crashing the application. I also have some doubts about whether you should attach to a specific hub (using its instance) or whatever you should bind to the current hub retrieving it everytime you need it (using the `HubAdapter` proxy), but it probably depends on what you want to achieve with that code

**Comment by ninze** [comment]
The docs are somewhat unclear about how to add integrations either. It says that integrations should be added using the `integrations` option, however it doesn't say how this option should be used. Is it an array of class names, objects, strings, or...?

Reading the docs I found RequestIntegration, ErrorListenerIntegration, ExceptionListenerIntegration, FatalErrorListenerIntegration. I assume the last 3 bind their own error handlers, so I would need to add back RequestIntegration?

I think there should be a separate option in Sentry that prevents binding error handlers without removing all default integrations. The list of default integrations can change in future, and now the responsibility for adding back all the defaults (except error handlers) is left to the end user.

It is also unclear why RequestIntegration and ErrorListenerIntegration are listed under "Core" in the docs, while the other 2 are listed separately.

**Comment by ste93cry** [comment]
>I think there should be a separate option in Sentry that prevents binding error handlers without removing all default integrations. The list of default integrations can change in future, and now the responsibility for adding back all the defaults (except error handlers) is left to the end user.

I agree, I'm working on porting to the PHP SDK the same behavior of the `integrations` option of the JS SDK which allows the value to be a lambda that will receive the list of default integrations and will return the updated list. This way filtering out integrations will be as easy as checking each item of the list with `instanceof`. Until then however, you're correct in saying that it's responsibility of the user to keep its list of integrations up-to-date with what's in the code of the library

**Comment by B-Galati** [comment]
@ninze FYI I created a library that can help you setting up Monolog with Sentry SDK: https://github.com/B-Galati/monolog-sentry-handler.

**Comment by B-Galati** [comment]
The Symfony guide ideas can be re-used with any framework/solutions.

**Comment by ninze** [comment]
@ste93cry any idea why `Sentry\Monolog\Handler` is pulling extras from `$record['context']['extra']` instead of `$record['extra']`, which seems to be the default place for "extra" data in Monolog as per [this doc](https://github.com/Seldaek/monolog/blob/master/doc/message-structure.md)?

**Comment by ste93cry** [comment]
Since `$record['extra']` is populated by the processors we may pull unwanted data from it. Instead, `$record['context']['extra']` is populated by the user and so are more safe and we can assume that that data is there to be captured. This topic is controversial and this is why in `3.0` we will not pull any information out-of-the-box from structured data leaving the implementation details to the user. We could not stop doing it now because we would broke BC

**Comment by ninze** [comment]
@ste93cry sorry for so many questions, but you seem to know this project pretty well...  :)

The Monolog handler requires an instance of `Hub` in order to log messages. On the other hand, the only purpose of `SentrySdk` class is to store / retrieve a static instance of `Hub`. In a way, `SentrySdk` acts as a global var to store current hub.

Since I prefer DI way of doing things instead of using global vars, I am wondering why not create an instance of `Hub` (possibly define a service) and use it everywhere (including Monolog) instead of `SentrySdk` static functions?

**Comment by ste93cry** [comment]
Well, the PHP SDK doesn't use any DI container because that's the job of an application and not of a library, but since there can be multiple hubs but only one set as current there must be somewhat that stores its instance and act as a sort of singleton managing it. This is the main reason I would avoid to depend on a specific hub instance: if the active hub changes under the hood you will not know it and you will use the wrong one. The `HubAdapter` proxy released with version `2.2` was introduced to let users typehint against the `HubInterface`, not worry about the `SentrySdk` class and be sure that the active hub is always the one that you will use. Let me know if I need to clarify more my answer

**Comment by enumag** [comment]
Any news on this? Should I use [`Sentry\Monolog\Handler`](https://github.com/getsentry/sentry-php/blob/master/src/Monolog/Handler.php) or [`BGalati\MonologSentryHandler\SentryHandler`](https://github.com/B-Galati/monolog-sentry-handler/blob/master/src/SentryHandler.php)? What should I use for the `default_integrations` and `integrations` options?

**Comment by ste93cry** [comment]
> Should I use [`Sentry\Monolog\Handler`](https://github.com/getsentry/sentry-php/blob/master/src/Monolog/Handler.php) or [`BGalati\MonologSentryHandler\SentryHandler`](https://github.com/B-Galati/monolog-sentry-handler/blob/master/src/SentryHandler.php)?

It depends on your needs: if it's enough for you to log events using Monolog without thinking about the breadcrumbs and custom extra data then the first handler should be fine, otherwise you can either implement your own version of the handler based on your needs or see if the one from @B-Galati is enough for your use case

**Comment by lucian303** [comment]
Is there a way to get this handler to show stacktraces? I can get additional data w/ a rough stacktrace if I use `BGalati\MonologSentryHandler\SentryHandler`, although the json is not formatted nicely in the UI like it used to be with the old raven library. With the default handler, I get nothing no matter what I've tried. The readable stacktrace is the main reason to use sentry in the first place.

**Comment by B-Galati** [comment]
You can have complete stack trace if you configure monolog to include stacktrace.

**Comment by lucian303** [comment]
@B-Galati I'm not sure what you mean. I get a stacktrace from monolog in every other handler's output (like a plain text file) without any configuration. What specific configuration are you talking about to enable stacktraces in Sentry?

**Comment by ste93cry** [comment]
As you can see [here](https://github.com/getsentry/sentry-php/blob/407573e22e6cc46b72cff07c117eeb16bf3a17de/src/Monolog/Handler.php#L54), we expect the `exception` key to log its stacktrace. Are you expecting to see the stacktrace in Sentry without an exception?

**Comment by lucian303** [comment]
Thanks. That's what I was missing.

**Comment by B-Galati** [comment]
I was talking abouth this option: https://github.com/Seldaek/monolog/blob/69b585feff23e6a3811b17c83efa0af936450e2b/src/Monolog/Formatter/LineFormatter.php#L47

That allows to log stacktrace in breadcrumbs.
