### ISSUE TITLE
JS: call undefined function in console doesn't call sentry

### ISSUE THREAD

**Issue by GhalebKhaled** [getsentry/sentry-docs#1126]
Hi,
I was following the basic example, and reached here:
https://docs.sentry.io/error-reporting/quickstart/?platform=browsernpm#capturing-your-first-event
I wasn't able to get the error in Sentry, while I could get one happened in my javascript file (in the concatenated `main.js`)
So I was wonder if I'm missing anything to be able to catch all errors everywhere?

**Comment by robolmos** [comment]
Attempting to trigger an error in Chrome 81 via DevTools' console does not invoke window.onerror handler, guessing because console catches the errors.

The docs should be updated to invoke an error via console like this (confirmed working in Chrome 81 and Sentry):

`window.setTimeout(function(){myUndefinedFunction();}, 0);`

Same applies to the new account setup wizard on Sentry.io.
