### ISSUE TITLE
Docs is showing preview package versions for install

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#11716]
### Steps to Reproduce

We made a preview release of the .NET SDK: https://github.com/getsentry/sentry-release-registry/commit/f2d6a8c924e038575f47c1cb040534e4bc292e11

Now the docs is suggesting that to be installed:
![Image](https://github.com/user-attachments/assets/4c984d61-cce2-4eff-beb9-4bb132c2ff8f)

Note, this was the default behavior of the docs since ~2019 when we introduced release registry to the docs. Because customers can experience challenges on their first attempt to use Sentry so that's not ideal

[Also note that a new version was shipped 13 hours ago](https://github.com/getsentry/sentry-release-registry/commits/master/), but docs still shows the preview (and older) version:
![Image](https://github.com/user-attachments/assets/9e26de61-3d1b-459e-9137-d238aaa68fb3)

### Expected Result

Docs excludes preview versions. For example, if version includes `-`, skip it.

### Actual Result

preview version showed up

**Comment by bruno-garcia** [comment]
There's actually a new version published yesterday: https://github.com/getsentry/sentry-release-registry/commit/322d710a269582f81c484f08a96fe723f7354ad5

https://github.com/getsentry/sentry-release-registry/blob/bfb30041f42e6f439de04c31889dd1a660345a63/packages/nuget/Sentry.AspNetCore.Blazor.WebAssembly/4.13.0.json

And it's still showing the preview version:
![Image](https://github.com/user-attachments/assets/fccc309f-98d9-4045-b915-0ffe9dd4279f)

**Comment by Lms24** [comment]
@bruno-garcia did we bump from 4.x to 14.x on purpose? 

The reason this version is shown here is because the craft release registry target compares what is currently in `latest.json`, which is `14.12.1-dump1` against the version to be released. In this case, that was `4.13.0`. Our comparison compares the major versions and immediately returns because `14 > 4`.

In case this was a mistake, I think we need to manually clean up the release registry which should fix the issue. Let me know if you want to do it, otherwise I can also take a look.

**Comment by bruno-garcia** [comment]
> In case this was a mistake, I think we need to manually clean up the release registry which should fix the issue. Let me know if you want to do it, otherwise I can also take a look.

Right the `14.` was a mistake. But since it was a preview build `-dump1` I didnt' think this would be an issue because we used to ignore preview builds on the docs and wizard.

> Let me know if you want to do it, otherwise I can also take a look.

I'd really appreciate if you could help me with this 🙏 Thank you Lukas!
