### ISSUE TITLE
Wrong param in start_span, 'name' should be 'description'

### ISSUE THREAD

**Issue by Rasmus-S-Kristensen** [getsentry/sentry-docs#11929]
### SDK

Python SDK

### Description

Page: https://docs.sentry.io/platforms/python/tracing/instrumentation/custom-instrumentation/

Several examples of this:
`with sentry_sdk.start_transaction(op="task", name="Eat Pizza"):`

This causes a runtime exception: `Span.__init__() got an unexpected keyword argument 'name'`

### Suggested Solution

Update examples

**Comment by szokeasaurusrex** [comment]
@Rasmus-S-Kristensen Please see [this section](https://docs.sentry.io/platforms/python/tracing/instrumentation/custom-instrumentation/#using-a-context-manager), specifically this note:

![Image](https://github.com/user-attachments/assets/16933ddb-fd88-43ca-a862-d5861f196a61)

Our docs pages document the latest versions of our SDKs, unless otherwise noted. Most likely, you are using an older version of the Sentry SDK which only supports the `description` parameter. 

Since the page is accurate for the latest SDK versions (above 2.15.0), I am closing this issue. Please let us know if you have any other feedback.

**Comment by Rasmus-S-Kristensen** [comment]
I stand corrected - thanks for the clarification :)
