### ISSUE TITLE
RQ Integration with Django not highlighted in RQ docs

### ISSUE THREAD

**Issue by danaspiegel** [getsentry/sentry-docs#2007]
If sentry is used with the standard django integration (`SENTRY_DSN` in settings) and RQ is used with `django-rq` to provide Django/RQ integration and the `rqworker` management command is used to run the RQ workers, then the `SENTRY_DSN` setting is automatically used and Sentry RQ integration is enabled by default.

See: https://github.com/rq/django-rq/blob/6a2430da44404644078e710bafb5b2d7eb395a0a/django_rq/management/commands/rqworker.py#L69

Additionally, in the Sentry web app console, there's a notice to enable the RQ integration even when the above integration is active.

**Comment by dcramer** [comment]
@untitaker maybe you can help here

**Comment by untitaker** [comment]
@danaspiegel We have decided not to encourage this kind of initialization as having multiple ways to initialize the SDK is harder to provide support for. I wish RQ would stop doing this and just let the SDK handle integration with the ecosystem (not the other way around), but it doesn't seem like they're going to anytime soon: https://github.com/rq/rq/issues/1003#issuecomment-441345373

Note that we explicitly recommend disabling RQ's initialization methods in our docs, partly also because it used to automatically detect the `SENTRY_DSN` envvar (an environment variable already used by our SDK) and double-initialize the SDK (discarding previous settings). This actually appears to still be the case as prior integrations are disabled when calling `init()` again (as RQ does)

>there's a notice to enable the RQ integration even when the above integration is active.

I can't quite explain why this happens but I'd imagine it's because of something RQ does.
