### ISSUE TITLE
PHP/Symfony Docs are Confusing

### ISSUE THREAD

**Issue by PeloWriter** [getsentry/sentry-docs#3479]
## Issue

This an issue with:
Platform Docs
Platform/SDK documentation (Which one?)
PHP/ Symfony

## Description
Mentioned in https://github.com/getsentry/sentry-docs/pull/3470:
I find the current structure of the guide for Symfony confusing: there's Config and Configuration sections, there's constant cross-reference to content related to the generic PHP SDK, there's no line between what's responsibility of the Symfony bundle and what belongs to the base SDK...
### Suggested Solution

Audit to identify areas of confusion/inaccuracy; refactor to adopt common content so inheritance works correctly (the main platform appropriately displays for Symfony and Laravel, with the guides overwriting where needed)

**Comment by Jean85** [comment]
This is still valid.

**Comment by stayallive** [comment]
@Jean85 I think I've patched things up a bit with #4638, what are other areas we could improve here?

The changes are live so you can check them out here: https://docs.sentry.io/platforms/php/guides/symfony/configuration/.

/cc @ste93cry

**Comment by Jean85** [comment]
My comments:
 * `%kernel.build_dir%` has been added to the default values of `in_app_exclude`; it's valid only for newer SF versions, since 5.2: https://github.com/symfony/symfony/pull/36515
 * `project_root` is an old option dropped in `sentry/sentry` 3, right?
 * `listener_priorities` was dropped in the bundle v4
 * Transport page talks about the base SDK, even if we're in the Symfony dedicated pages
 * we suggest as an example the Guzzle adapter, which no longer use as default, and is v6, which is now superseeded
