### ISSUE TITLE
Discover [set-custom-tags] code examples gone

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-docs#3584]
I think the include might be broken here
![image](https://user-images.githubusercontent.com/363802/118229779-dfe9e180-b48c-11eb-951b-da0f6eb6466b.png)

**Comment by PeloWriter** [comment]
Thanks for pointing this out. I've fixed the include statement, so that correct code sample displays. It now defaults to the old behavior, where you select a language from the list. 

However, once you select the language, the page moves you back up to the top, so you must then scroll back down to where the sample displays. This appears to be a tooling issue on the product pages. So, it's fixed in terms of correct content, but reveals an issue with content display.

**Comment by PeloWriter** [comment]
Fixed (the correct path for the include in 3589).
