### ISSUE TITLE
Android SDK upload symbols docs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#3743]
Talk about gradle plugin instead of `sentry-cli` (suggest the latter further down as an alternative):
https://docs.sentry.io/platforms/android/using-ndk/#symbolicate-stack-traces

We have steps about installing the Gradle plugin in the ProGuard bits:
https://sentry-docs-git-update-debug-information-files-ia.sentry.dev/platforms/android/proguard/

Perhaps we can generalize this and 'include' in both NDK and ProGuard pages?

We link to this doc and it's missing code snippet for Android. But we even want to link to it?
http://docs.sentry.io/platforms/android/data-management/debug-files/upload/

**Comment by marandaneto** [comment]
> Talk about gradle plugin instead of `sentry-cli` (suggest the latter further down as an alternative):
> https://docs.sentry.io/platforms/android/using-ndk/#symbolicate-stack-traces

yes, I don't even remember about that, good call.

> We have steps about installing the Gradle plugin in the ProGuard bits:
> https://sentry-docs-git-update-debug-information-files-ia.sentry.dev/platforms/android/proguard/
> 
> Perhaps we can generalize this and 'include' in both NDK and ProGuard pages?

yes, the idea is to be something similar to Flutter -> https://docs.sentry.io/platforms/flutter/upload-debug/
a Debug Symbol section that explains everything, I guess there's an issue about that already, to generalize and make a common options for debug symbols.
https://github.com/getsentry/sentry-docs/pull/3735/files but looks like its been closed.

> We link to this doc and it's missing code snippet for Android. But we even want to link to it?
> http://docs.sentry.io/platforms/android/data-management/debug-files/upload/

I think it's still useful, but we definitely should focus on the Gradle plugin, the reason is, not every native lib is built within the Gradle solution hence no debug symbols would be there, so if people do it outside of the gradle solution or any other build solution for Android, they can still do it with sentry-cli.
eg Bazel -> https://developer.android.com/codelabs/bazel-android-intro#0

**Comment by PeloWriter** [comment]
> Talk about gradle plugin instead of sentry-cli (suggest the latter further down as an alternative):
> https://docs.sentry.io/platforms/android/using-ndk/#symbolicate-stack-traces

I have this change as a [draft PR](https://github.com/getsentry/sentry-docs/pull/3744/files) - I'll change it to a normal PR, so we can get this change merged.

> I guess there's an issue about that already, to generalize and make a common options for debug symbols.

This change became a larger effort that requires coordination across teams, we we're working on a plan to ensure we've got the right folks with time to work on it.

**Comment by bruno-garcia** [comment]
> Due to current limitations in how sentry-native works, it cannot yet identify native libraries loaded directly from .apk files. Instead, it needs to have access to the extracted libraries on the file system. This functionality is disabled by default when using an Android Gradle Plugin >= v3.6.0, and it needs to be enabled with the extractNativeLibs configuration option.

This is not longer up-to-date as of version 5.0.0 of the Android SDK (which includes sentry-native 0.4.9).

I also think ideally we'd move notes like:

> If you are using sentry-android version earlier than 3.1, you must manually disable the...

To the bottom of the page, or a "troubleshooting page. We're on version 5.0.0 already so for limitations of older versions, ideally they wouldn't be the first thing we show on such pages.

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-docs/pull/4058/files

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-docs/pull/4058 has been merged and opened https://github.com/getsentry/sentry-docs/pull/4096 so we can close this issue
