### ISSUE TITLE
Versioned Docs

### ISSUE THREAD

**Issue by gormus** [getsentry/sentry-docs#3881]
### Core or SDK?

Platform/SDK

### Which part? Which one?

getsentry/sentry-php

### Description

This is rather a feature request actually.

Due to dependencies, and locked versions, I cannot use the latest Sentry packages in my Drupal project.

I think it would be really helpful to access the documentation relevant to the version I use.

Could you make the documentation site to reflect the selected version, instead of displaying the latest all the time?

### Suggested Solution

The user selects the platform they are interested in, they would see the latest documentation for the platform; but the user would be able to change the version from a drop-down list to access to the documentation matching the version they use in their project.

Here's an example (not the best I am afraid): https://drupal-graphql.gitbook.io/graphql/ (see the version links below the logo)

**Comment by jgillard** [comment]
I just hit this issue when trying to enable Replay on v7. I'm on v7 because I'm using the Loader script, which is not on the latest version of the JS SDK: https://github.com/getsentry/sentry-javascript/issues/12187. The getting started instructions have changed between v7 and v8 and it took me a while to realise the live docs had the wrong info for what should be a supported setup.
