### ISSUE TITLE
Change PlatformLink behavior so list is constrained to supported SDKs

### ISSUE THREAD

**Issue by Lorenzohidalgo** [getsentry/sentry-docs#3969]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Documentation

### Description

At the end of the [User Feedback documentation](https://docs.sentry.io/product/user-feedback/?_ga=2.236532673.1773453541.1627844440-653201474.1626270940) there is a [link ](https://docs.sentry.io/platform-redirect/?next=/enriching-events/user-feedback/) to the supposed configuration documentation. Once clicked you are redirected to chose a platform, by selecting flutter you are redirected to a [Page Not Found](https://docs.sentry.io/platforms/flutter/enriching-events/user-feedback/). Is this feature available for the Flutter SDK?

### Suggested Solution

Update to correct documentation link or delete option from the available platforms. It also happens for: Dart, Kotlin, Native, Perl & Ruby.

**Comment by PeloWriter** [comment]
This feature is not currently supported for these platforms. We'll fix the link. Thank you.

**Comment by PeloWriter** [comment]
What is happening here is that a user who doesn't yet have a platform in context is directed to the platform picker, which is a comprehensive list. If the user selects a platform that doesn't support the feature, they end in a 404 page. 

We need to constrain the list of platforms to those that support the feature. This will require tooling support; adding the "enhancement" label so that it's incorporated into future work on our tooling.

**Comment by a-hariti** [comment]
Is this still relevant on Next.js @PeloWriter?

If so, please provide a concrete repro
