### ISSUE TITLE
Relay settings documentation does not match options in settings

### ISSUE THREAD

**Issue by noahduncan** [getsentry/sentry-docs#4031]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Relay

### Description

The documentation for Relay does not mesh up with the configuration options I see in my account.  To configure relay the documentation says to add a key in the Relay section of the config, but I don't have a Relay section.  I'm not sure what to do!

Let me know if I can provide any more info to help out!

### Suggested Solution

Make docs for Relay mesh with current state of settings UI.

**Comment by imatwawana** [comment]
@noahduncan are you on a Business or Enterprise plan? I ask because Relay is only available on those plans, and not on Developer or Team plans.

**Comment by noahduncan** [comment]
@imatwawana Aha! Your guess is correct. We are on a Team plan. Thank you!

Now that you say it, I see there is a little note on https://docs.sentry.io/product/relay/ stating that managed mode is only available on Business and Enterprise.  That answers my question, we can set it up in proxy mode, no problem.

However, I still think the documentation is a little unclear.  Maybe emphasizing that note a bit more would be good, or adding it to the section specifically about modes and the configuration through sentry.io would make it easier to navigate.  

Another option would be to leave the configuration setting in the config for Teams, but have the little icon that indicates it is a feature I don't have access to.   Personally, I LOVE that little icon as I can see what features are out there that we could upgrade to.

**Comment by noahduncan** [comment]
Amazing, I see you all are adding some notes to the documentation for relay around the different modes.  Already I understand what to do better.

Thank you!

**Comment by imatwawana** [comment]
I'm glad things are clearer already! I don't have a timeline for when that issue will get worked on, so in the meantime I'll add/move notes about plans and modes. The note size is fixed, but hopefully adding or moving them will make them more obvious. I'll link that PR to this issue.

We are also working on adding more "empty states" in the application so that folks can see what features they might want to add. I'm not sure if this particular one is on the roadmap or not, but I'll check and/or log an issue for the right team.
