### ISSUE TITLE
React Functional Component initialization

### ISSUE THREAD

**Issue by richardhao1995** [getsentry/sentry-docs#4426]
### Core or SDK?

Platform/SDK

### Which part? Which one?

React

### Description

When trying to initialize a test error for Sentry through React, the test code of 

`return <button onClick={methodDoesNotExist}>Break the world</button>;`

doesn't work in a functional component since it won't compile within React. 

Is there another way to send the first test error and initialize Sentry? I'm using React version 17.

Am fairly new to React so please forgive me if I'm doing something wrong.

Thanks!

Richard

### Suggested Solution

For me, putting in an arrow function which throws an error seems to force an Unhandled error.

`<button
          onClick={() => {
            throw new Error("Unexpected Error");
          }}
        >
          Break the world
        </button>`

**Comment by AbhiPrasad** [comment]
> since it won't compile within React

Are you using typescript or do you have strict eslint rules set up? This might be what is preventing the bundle from being generated. [Running a quick repro, we can see that the error seems to be captured fine](https://codesandbox.io/s/romantic-borg-keo6c?file=/src/index.js) (it's being logged to the console).

We did it this way so that things would break as soon as you open your application, instead of having you have to click a button to cause an exception.

**Comment by richardhao1995** [comment]
I am not using typescript, I do actually get the same error as the repro link however Sentry was not receiving the error.
