### ISSUE TITLE
Create a plan comparison page

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry-docs#4483]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Pricing

### Description

Currently, the only comparison page available is the https://sentry.io/pricing/ page, which is not very clear on which features are available on each plan.

### Suggested Solution

Create and maintain a features comparison page, similar to this from Google Workspace: https://support.google.com/a/answer/6043385?hl=en

**Comment by rbisol** [comment]
We don't get it often, maybe less than one per month. From what I see the two main issues are:
- Confusion between Authentication and SSO. Some users think they can use Azure as SSO on the team plan.
- It is hard to see the advantages of upgrading to Business.

**Comment by imatwawana** [comment]
Thanks for the clarification! To your points:
- The inclusion of Azure under Authentication on the pricing page is confusing and FWIW I struggle with keeping the difference between authentication and SSO straight in my head. I think there are a few possible solutions for that. 1.  Add something on the pricing page that clarifies that Azure isn't SSO in that context (perhaps literally putting "not SSO" in brackets next to it). 2. Add a blurb in the docs about the difference between authentication and SSO and link to it from the word "Azure" (and maybe also from "Google" and "GitHub") on the pricing page. or 3. Just remove Azure from that list entirely (suggestion from one of the devs)  because AFAIK not many customers use Azure for just authentication. 
- This strikes me as being a design/content issue on the pricing page. There's been feedback that the way the page works makes it hard to tell really quickly what's available on each plan but maybe not enough Biz-only features are even included on the page to show off that difference between Biz and Team. 

IMO, these seem like two things that can be fixed on the pricing page much more easily and reliably than creating a new resource in Docs that we'll struggle to maintain. What do you think?

**Comment by imatwawana** [comment]
@rbisol - just checking back in. See my comments above.
