### ISSUE TITLE
Capacitor SDK docs don't point user to native symbol upload

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#4731]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Capacitor

### Description

https://docs.sentry.io/platforms/javascript/guides/capacitor/

No where on the docs there is a reference to uploading symbols. There's a note on the top

> Sentry's Capacitor SDK enables automatic reporting of errors, exceptions, and messages. It includes native crash support on iOS and Android.

Which would be best as a Features List similar to other SDKs.

### Suggested Solution

And after the Verify step, we need to mention that for proper native support, native symbols must be uploaded.
Ideally that'd be part of the 'sourcemap' upload step, just as additional sentry-cli calls.

**Comment by lucas-zimerman** [comment]
I have tested it here: https://sentry.io/organizations/sentry-sdks/issues/3125267581/events/e94e4d20242443e096a1500d7fc852b7/?project=5522756

Since we are dealing with an Xcode project maybe, we should add this tutorial to capacitor https://docs.sentry.io/platforms/apple/dsym/

I might have missed something but I haven't found similar docs for Android, so this issue may only apply for iOS?
