### ISSUE TITLE
Not clear API document for release process

### ISSUE THREAD

**Issue by smilexu** [getsentry/sentry-docs#509]
Following the release process by document described, there is something really confused me
1. create release
There are two different approach url apparently
https://docs.sentry.io/learn/releases/?platform=node#create-deploy 
`curl https://sentry.io/api/0/organizations/:organization_slug/releases/ \`
and
https://docs.sentry.io/clients/javascript/sourcemaps/  
`curl https://sentry.io/api/0/projects/:organization_slug/:project_slug/releases/ \`

Seems both of them works, what is the different,  which one is the recommended one  ? And how to specify project with first approach ?

2. upload sourcemap
I followed guide from https://docs.sentry.io/clients/javascript/sourcemaps/ works fine. 

3. tell sentry about the deploy
That is the only document I found https://docs.sentry.io/api/releases/post-release-deploys/, the question is how to specify the project I deployed ? Imagine we have multi projects under some organization, how do deal with that ?

Others:
After I did 1,2,3 steps as above, let us say I told sentry I made a deployment for `staging` environment. But that release is not listed in `staging` environment, they can only found in Environment All, until there is some issue catched there. That is really confusing, since I will expect to get the new release on specific environment list immediately,  right after I make the sentry release. Or I misunderstood how sentry works ?

Looking forward to get answer soon. Thanks.

**Comment by smilexu** [comment]
@markstory for some devops reason, we prefer the API the way instead of sentry-cli.

Could you explain more about my last question ?

> After I did 1,2,3 steps as above, let us say I told sentry I made a deployment for staging environment. But that release is not listed in the list of staging environment, they can only found in Environment All, until there is some issue catched there. That is really confusing, since I will expect to get the new release on specific environment list immediately, right after I make the sentry release. Or I misunderstood how sentry works ?

Is that how sentry works or I did anything wrong ?

**Comment by markstory** [comment]
> Is that how sentry works or I did anything wrong?

Yes that is how Sentry works. It requires events to stitch releases and environments together.

**Comment by patocallaghan** [comment]
@markstory we are using the `https://sentry.io/api/0/projects/:organization_slug/:project_slug/releases/` API endpoint due to our dependence on a third party library in our deployment process. 

It appears there are discrepancies with these two endpoints if you are trying to associate commits with a release.

For example if I send this request payload to the following API endpoint the release is created but it doesn't associate my specified commit with the release. 

`https://sentry.io/api/0/projects/:organization-slug/:project_slug/releases/`

```json
{
    "version": "ae652002514f7a1dfe2dc7d79e7fde0d8fc91234",
    "refs": [
        {
            "repository": "org-name/repo-name",
            "commit": "ae652002514f7a1dfe2dc7d79e7fde0d8fc91234"
        }
    ]
}
```

Screenshot from Sentry
![image](https://user-images.githubusercontent.com/685034/56380273-abea5680-6209-11e9-8428-1dee828d277e.png)

However, if I send this payload to this API endpoint it creates a release and correctly associates my commit with that release.

`https://sentry.io/api/0/projects/organizations/:organization-slug/releases/`

```json
{
    "version": "d8bc7e7960ae3be3e045d0f999d0b503bb611234",
    "refs": [
        {
            "repository": "org-name/repo-name",
            "commit": "d8bc7e7960ae3be3e045d0f999d0b503bb611234"
        }
    ],
    "projects": ["repo-name"]
}
```
Screenshot from Sentry
![image](https://user-images.githubusercontent.com/685034/56380196-6cbc0580-6209-11e9-9d69-37538d16330d.png)

Is there some difference I need to be aware of between these endpoints? Is it a bug in my request or is it a bug in the endpoint?

**Comment by markstory** [comment]
The endpoints take different parameters. The project endpoint does not accept `refs` and requires you to pass each commit individually through the `commits` property. The organization level endpoint accepts `refs` and offers more automation around fetching commit data from repository providers.

If possible I would recommend using the organization level endpoint or `sentry-cli`.

**Comment by patocallaghan** [comment]
@markstory thanks for the clarification. Modifying my request to send the following worked:

```json
{
    "version": "95b5f225e4df2dc2840a93846dd40f31775e1234",
    "commits": [
        {
            "repository": "org-name/repo-name",
            "id": "95b5f225e4df2dc2840a93846dd40f31775e1234"
        }
    ]
}
```

For now, to change to using the organization endpoint may be an issue as it's not our code but the [ember-cli-deploy-sentry](https://github.com/dschmidt/ember-cli-deploy-sentry) third-party plugin.

If I was to float the idea of changing to use the organizations endpoint in that plugin to its author, what's the main selling point over the existing one?

**Comment by markstory** [comment]
You don't need to parse all the commits for the release. Instead you only need the head commits for each repository.

**Comment by kelsonm** [comment]
I've been looking like mad at solving this issues. 
Changed my payload as recommended by @markstory and works like a charm.

**Comment by PeloWriter** [comment]
Looks like Mark has helped resolve this. Closing.
