### ISSUE TITLE
https://docs.sentry.io/product/user-feedback/ has a broken "configure" link

### ISSUE THREAD

**Issue by jzaefferer** [getsentry/sentry-docs#5477]
### Core or SDK?

Platform

### Which part? Which one?

Various

### Description

At the bottom of https://docs.sentry.io/product/user-feedback/ is a link to https://docs.sentry.io/platform-redirect/?next=/enriching-events/user-feedback/ with the link text "configure". From there I selected "React Native", which then leads to this 404 page: https://docs.sentry.io/platforms/react-native/enriching-events/user-feedback/

Clicking around, some others are also missing: https://docs.sentry.io/platforms/kotlin/enriching-events/user-feedback/ https://docs.sentry.io/platforms/native/enriching-events/user-feedback/ https://docs.sentry.io/platforms/perl/enriching-events/user-feedback/

The one for ruby exists, but its pretty empty: https://docs.sentry.io/platforms/ruby/enriching-events/user-feedback/

### Suggested Solution

Add the missing content? If the platform isn't supported, make that clear.

**Comment by imatwawana** [comment]
Hi @jzaefferer, while it's not the ideal user experience, this is the expected behaviour when a feature isn't supported for a platform/language, which is the case for the platforms you pointed out (React Native, Native, Kotlin, Perl). As for Ruby, the feature is supported for Rails but not Ruby, but it means this page has to be displayed for Ruby. But I see how we left that in a bit of a confusing state, so we'll need to add something to clarify that.

**Comment by jzaefferer** [comment]
The page with all the platform links says "The page you are looking for is customized for each platform. Select your platform below and we'll direct you to the most specific documentation on it.". How about an extra hint like "Unsupported platforms will show a 404 page"?

**Comment by imatwawana** [comment]
While we need to figure out a better long term solution for these situations, hopefully #5493 addresses some of your concerns.

**Comment by jzaefferer** [comment]
Looks good to me 👍 Now I'll just have to wait for the React Native support 😅
