### ISSUE TITLE
[Python] Fix duplicate content in integration guides

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-docs#5669]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Python SDK, all the integration guides

### Description

We have around 20 integrations in the Python SDK. 
We have one guide for each of our integrations, like this one:
https://docs.sentry.io/platforms/python/guides/django/

The guide shows how to install, configure and verify a correct installation of a integrations. Plus sometimes describes the behavior of the integration.

This is good. 

But all the documentation that is not specific to an integration, but relate to the general Python SDK and is the same for all the integrations is duplicated inside the integration guides. 

See this one example for "Set transaction name":
https://docs.sentry.io/platforms/python/guides/django/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/bottle/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/celery/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/chalice/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/falcon/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/fastapi/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/flask/enriching-events/transaction-name/
https://docs.sentry.io/platforms/python/guides/pyramid/enriching-events/transaction-name/

And here is the page in the "normal" Python documentation:
https://docs.sentry.io/platforms/python/enriching-events/transaction-name/

This is **very** confusing. If I am in the Django guide and I search for "transaction name" and then get a result of the Flask guide for transaction naming I ask myself: "Is this the same as it is in Django? I probably have to find the Django one. But there is also a general Python page for transacting naming... Does it work differently in Django than in normal Python?"

### Suggested Solution

Keep the "Start Page" of the integration guides with the same URLs:
https://docs.sentry.io/platforms/python/guides/django/

We then put all the integration guides in the the left sidebar menu so the structure is like this:
```
SENTRY FOR PYTHON
- Getting Started
- Integrations
    - Django
    - Flask
    - FastAPI
    - ...
- Configuration
- ...
```

These integration pages contain everything that is Integration specific (which is most of the time just the installation and some description of the behavior. I also guess this is the page that people find on Google)

We remove all the duplicate pages and make a permanent redirect (HTTP 301 Moved Permanently) on those URLs to the standard Python page of that page. This way the duplicate pages will be dropped from the Google index and only the "normal" Python page will show up in search results.

Additionally we remove the "Related Guides" from the right sidebar (see for example here: https://docs.sentry.io/platforms/python/) because it noisy and removed focus from the "On this page" section above. 

The list of guides is now in the main sidebar on the left, so no need to have it in two sidebars.

**Comment by imatwawana** [comment]
@lizokm and I will need to have an in-depth conversation about this and we'll circle back.

Also, can you please [make your GitHub profile public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership). This ensures that issues raised by Sentry employees don't get counted for our triage SLOs. Thanks!

**Comment by lobsterkatie** [comment]
What you're proposing is more or less what the structure used to be, before the big docs revamp spearheaded by Fiona and Cramer... two years or so ago, I think?

I'm obv not in the docs department, and ultimately I will leave this to the experts, but I have been part of both docs overhauls (and at least one attempted but later abandoned overhaul) which have happened in the last 4-5 years, so here's my two cents:

(And forgive me if some of what I'm saying you already know, @antonpirker. I'm replying specifically to your issue description, but also just wanting to get my thoughts down for posterity.)

Part of the issue here is that the line between what counts as an integration and what counts as a separate SDK can get pretty fuzzy, and differs from platform to platform. Over the years, at least in JS land, we've moved from the model of framework-specific integrations used as part of a single SDK to framework-specific SDKs which are wrappers around one or more base SDKs. (So, for example, for a Vue app you used to use `@sentry/browser` with a `Vue` integration, but we instead now have a full-blown `@sentry/vue` SDK, which delegates most of its work to its dependency, `@sentry/browser`. Things which hook into non-framework libraries we've kept as integrations, so that you can use them with apps written in any framework. For example, we don't have `@sentry/postgres`, but instead have a `Postgres` integration which can be used with `@sentry/node`, `@sentry/nextjs`, etc. In Python land you have that distinction to a certain extent, too, in that Django gets its own "guide" whereas SQLAlchemy is listed under `Configuration > Integrations`, even though you use both by adding to the same `integrations` array in `sentry_sdk.init`.) 

In any case, as we've moved to the separate SDK model, it's made more sense to present each one as its "own thing" - a sibling to `@sentry/browser` or `@sentry/node` - as opposed to a subsection of the browser or node SDK docs. And yes, I'm sure there's a little bit of JS SDK bias in the overall docs information architecture design, as the SDK docs in general are a little JS-biased. When Fiona was doing all of the rewriting and really trying to nail down the structure, JS was the test case, off of which all other platforms were modeled. 

Another issue is that while you're right about everything on the LH sidebar from `Enriching Events` on down (it's more or less identical regardless of framework), I think the stuff in the first two sections of the sidebar has more framework-specific differences scattered throughout then you'd think, so it's not immediately obvious how it would work if for each framework you tried to gather all of those bits in a single `Integrations > XXX` section separate from the main setup/config and performance docs.

All of that said, you're right that the current architecture has its challenges, too, starting with the fact that if I'm on page X in one framework's docs, and I click on a different framework in the RH sidebar, I'm taken back to `Getting Started`, rather than to the new framework's page X. Also, if you're in one of the framework-specific "guides," the platform selection menu in the nav bar shows that framework as the selection, but if I choose a different platform from the menu and then want to go back, my previously-selected framework-specific option isn't there. And as you say, search is confusing. (That's true across the entire docs site, though - it's a known issue that it just fundamentally doesn't work well. If we ever were to get a docs engineer, IMHO that'd be almost the very first thing they should work on.) 

Overall it's a tricky problem to solve, with no perfect solution. There are definitely arguments to be made for both options.

**Comment by antonpirker** [comment]
Hey @lobsterkatie, thanks for all the context! Very insightful!

So different platforms create the SDKs in a different way. "SDK per framework" vs "Integration per framework".
I think it is fine that there are different ways of doing things in different platforms. That's how the world is. 

Possible things we could do:
a) In Python we could decide to move most of the "guides" to https://docs.sentry.io/platforms/python/configuration/integrations/ and only have real "guides" for big integrations like Django. But maybe that confuses people even more.
b) Think about having a different documentation structure for different platforms. Right now the same structure is used for all platforms. Which helps to have a consistent feel over all platform documentations but also makes editing documentation kind of hard, because you can potentially change the documentation of an entirely unrelated platform with your changes.

**Comment by hubertdeng123** [comment]
Looks like this issue is counted towards our triage SLO's, so I'm going to tag this as a backlog item to prevent this

**Comment by lizokm** [comment]
Hi @antonpirker, this is potentially a really sizable undertaking. @imatwawana and I will talk and get back to you about it before the end of Q4.

**Comment by antonpirker** [comment]
This has been implemented already. Closing it.
