### ISSUE TITLE
.NET: Misleading server-name description for dotnet

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-docs#5742]
### Core or SDK?

Platform/SDK

### Which part? Which one?

dotnet

### Description

The [server-name section](https://docs.sentry.io/platforms/dotnet/configuration/options/#server-name) that is shared between "python", "node", "ruby", "php", "java", "dart", "dotnet" has a misleading last line for dotnet.  **Most SDKs will attempt to auto-discover this value**.  You have to enable SendDefaultPii to get the server-name field for dotnet, while in python, you do not have to enable SendDefaultPii.  For node, there is no SendDefaultPii, but server-name still comes up.

### Suggested Solution

Maybe omit that line for dotnet, or add " if send default PII is active" to the end of the line for dotnet.

**Comment by imatwawana** [comment]
@Fwang36, I've opened [a PR ](https://github.com/getsentry/sentry-docs/pull/5764)to resolve this, so now the server-name description for [.NET](https://sentry-docs-git-fix-misleading-server-name-note-dotnoet.sentry.dev/platforms/dotnet/configuration/options/#server-name) would look like this and the [other SDKs](https://sentry-docs-git-fix-misleading-server-name-note-dotnoet.sentry.dev/platforms/java/configuration/options/#server-name) would look like this. Let me now if this works for you. I'm messaging you here because I can't seem to tag you on the PR.

**Comment by Fwang36** [comment]
Hey Isabel,

That looks good! Thanks for making the change

**Comment by imatwawana** [comment]
Great! I'm just waiting for an approval from the associated development team. Once I have that, I'll merge the change.
