### ISSUE TITLE
expandable sections in body text

### ISSUE THREAD

**Issue by imatwawana** [getsentry/sentry-docs#5748]
### Core or SDK?

Core Sentry product

### Which part? Which one?

All sections (core and platform)

### Description

The content on some pages can be very long and this can become overwhelming for a user.

### Suggested Solution

Add the ability to put content into expandable sections that a user can open or hide.

**Comment by lizokm** [comment]
Not sure how much of a lift something like this would be, but it would be great to be able to have collapsible paragraphs so that they pages could be shorter and people could just uncollapse the sections they were interested in reading about. That way, maybe we could also get rid of the right had nav and make everything less busy.

**Comment by untitaker** [comment]
We can implement this but I think there would be a bit of extra work involved in making this play nicely with links that have anchors (i.e. somebody links you to a specific section or paragraph, and the browser automatically scrolls to that section) which is something that happens quite frequently with links from google search results

**Comment by lizokm** [comment]
I'd love to talk more about this. I think having this as an option will be a BIG improvement to docs readability.
