### ISSUE TITLE
Sentry.Integrations.HttpContext does not exist

### ISSUE THREAD

**Issue by larsqa** [getsentry/sentry-docs#5883]
### Core or SDK?

Platform/SDK

### Which part? Which one?

JavaScript related SDK

### Description

I've seen several places mention `HttpContext`, to be more specific, `Sentry.Integrations.HttpContext`.
Example:
- [Next.js configuration](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/default/#httpcontext)
- [Data Scrubbing](https://docs.sentry.io/platforms/javascript/guides/capacitor/data-management/sensitive-data/)

After some timely research, I figured out that `HttpContext` doesn't exist, but rather [`Sentry.Integrations.Http`](https://docs.sentry.io/platforms/node/configuration/integrations/default-integrations/#http), which i have only found in the NodeJS documentation. 

### Suggested Solution

Stay consistent and rename all "HttpContext" occurences to "`Http` context" (note space and not capital in context) to remove any confusion. It would also be helpful linking to the documentation (e.g. missing on Data Scrubbing page) when "`Http`context" is mentioned.

**Comment by lobsterkatie** [comment]
Hi, @larsqa.

Perhaps you figured this out, because you closed the issue, but in fact both integrations exist - `Http` is an integration in the [node SDK](https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/integrations/http.ts), and `HttpContext` is an integration in the [browser SDK](https://github.com/getsentry/sentry-javascript/blob/master/packages/browser/src/integrations/httpcontext.ts).

**Comment by larsqa** [comment]
I closed this issue in favour of #5884
