### ISSUE TITLE
Unclear guidance on creating events in API Reference

### ISSUE THREAD

**Issue by moubry** [getsentry/sentry-docs#6054]
### Core or SDK?

Core Sentry product

### Which part? Which one?

API Reference

### Description

On the home page of the [API Reference](https://docs.sentry.io/api/), it says:

> The Sentry API is used for submitting events to the Sentry collector as well as exporting and managing data.

But as far as I can tell there are no published HTTP APIs for creating events.

### Suggested Solution

Remove verbiage about “submitting events” and explicitly explain why it is not supported since it seems like a reasonable thing to want to do with the Sentry API.

**Comment by AbhiPrasad** [comment]
Hey @moubry - sending events to Sentry is documented in our developer documentation, since we usually expect our users to use one of our SDKs to accomplish this. You can find the full details of that here: https://develop.sentry.dev/sdk/store/

We recommend though that you use an SDK with the `Sentry.send_event`/`Sentry.sendEvent` command so that you don't have to worry about formatting and handling rate limits (as event ingestion differs from the rest of the API).

**Comment by souredoutlook** [comment]
Just going to add to this @moubry that you can use `sentry-cli` to send events as well, this will also handle formatting and rate limits:

https://docs.sentry.io/product/cli/send-event/
