### ISSUE TITLE
No have docs for javascript SDK API

### ISSUE THREAD

**Issue by vitonsky** [getsentry/sentry-docs#6222]
### Core or SDK?

Platform/SDK

### Which part? Which one?

javascript

### Description

I trying to use sentry in project with several sentry instances. I have problem - one of instances is not sent events.
I go to read the docs on site https://docs.sentry.io/platforms/javascript/ to explore API, probably i have to create isolated instance instead of global singletone, but i can't found any info about how SDK works.

I don't understand
- What object `Sentry` is when i do `import * as Sentry from "@sentry/browser";`. Is this preconfigured "client"?
- How i can create isolated instance? I found that i may do `new Sentry.BrowserClient`, but this API [mention only on vue docs](https://docs.sentry.io/platforms/javascript/guides/vue/troubleshooting/), i can't found any info how i should work with new client

I even created instances of `BrowserClient` and `Hub`, but when i catch exception and set tags, the tags is not appear in sentry dashboard.

It looks that sentry suitable only for trivial cases where project have only one sentry instance. It is not our case, we need to configure how exceptions must be handled for each federated module. But docs site is not contains info about javascript SDK API

### Suggested Solution

Add docs about javascript API that have structure which answer questions

Examples of docs sites that have API docs:
- https://redux.js.org/api/api-reference
- https://effector.dev/docs/api/effector/
- https://reactjs.org/docs/react-api.html

**Comment by Lms24** [comment]
Hi @vitonsky, thanks for writing in! 

>It looks that sentry suitable only for trivial cases where project have only one sentry instance

That's primarily correct. We do not yet support MFE architectures "properly" but it's on our radar to fix in the long term. However, this is a very hard problem to solve so we can't make guarantees or give time frames at this time. There are a couple of ways that could help you get Sentry set up somewhat decently in your app:

* You already mentioned this but you'll need to configure clients and hubs manually, as shown in our [troubleshooting section](https://docs.sentry.io/platforms/javascript/troubleshooting/#using-a-client-directly). This works for all JS SDKs btw, not just for Vue.
* If errors aren't sent to the correct Sentry project, you might want to create a custom transport where you can determine manually where to send events to. This will probably require reading some code but [this example](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#custom-transports) should help you get started
* Some of our integrations however will only add content such as tags to the current hub (i.e. the one that's returned by `getCurrentHub`. Theoretically, you can use the `Sentry.makeMain` function to set a respective hub as the currently active "main" hub. However, it depends on your app if you can set this reliably.

Lastly, if you want to provide feedback about your MFE requirements on Sentry, feel free to leave a note in [this discussion](https://github.com/getsentry/sentry-javascript/discussions/5217).

**Comment by Lms24** [comment]
I'm going to close this issue as there isn't much we can do here now other than what we're already tracking in regard to MFE support.

**Comment by vitonsky** [comment]
> I'm going to close this issue as there isn't much we can do here now other than what we're already tracking in regard to MFE support.

My issue not about MFE, but about SDK API documentation.
I can't use sentry now, because i don't see what SDK contains. I see tutorials, but not javascript SDK functions and methods listing and description.

I've mention sites with javascript API docs above, i can add one yet another example http://fabricjs.com/docs/

Please, reopen this issue and review actual problem that i have.

I'm sure we have to add API docs on the docs site, to help sentry users understand how they can use sentry in their use cases.

**Comment by vitonsky** [comment]
@Lms24 i even can't found what `Sentry.makeMain` is, because docs site contains no info about this knob.
Let's improve docs for the whole community.

![Screenshot 2023-02-08 at 12-56-07 JavaScript](https://user-images.githubusercontent.com/86191922/217497711-590cd088-f39d-480d-b7c6-0f452b123c0f.png)

**Comment by vitonsky** [comment]
@lizokm please, reopen my issue to re-triage

**Comment by Lms24** [comment]
> My issue not about MFE, but about SDK API documentation.

I see, apologies, I misread your main intention of the issue. So, [we used to have API docs](https://getsentry.github.io/sentry-javascript/modules/browser.html) for v5 of the SDK but we don't have them anymore because our TypeScript version is too old to work with the API doc system we used. [Once we upgrade the TS version](https://github.com/getsentry/sentry-javascript/pull/6755) we can think about bringing them back but so far, there has been very little demand for that. 

> I'm sure we have to add API docs on the docs site, to help sentry users understand how they can use sentry in their use cases.

I agree that eventually, it might be worthwhile to have them, although our docs should cover 95% of the use cases in which Sentry is used (and I'd argue that they go beyond the "trivial" use cases).

> i even can't found what Sentry.makeMain is, because docs site contains no info about this knob.

Also true, but there's a reason for this: As I said, `makeMain` is a very sketchy API in the sense that it doesn't work well and depends a lot on the application it's used in. So we recommend trying it when people are searching for MFE support (we have various issues and discussions around this topic in the SDK repo) but without guarantees for success. 

Generally, we're always committed to improving docs. One area we need to improve is our search function for instance. Regardless, if you have a concrete idea, please feel free to open a PR - we're more than happy to review it.
