### ISSUE TITLE
Meaning of "Session Replay is now generally available. In the coming weeks this organization will not be able to ingest any new replays. Notify your organization owner to keep using Session Replay."

### ISSUE THREAD

**Issue by AlexanderBartash** [getsentry/sentry-docs#6300]
### Core or SDK?

Core Sentry product

### Which part? Which one?

SDK

### Description

I see this message on replay page "Session Replay is now generally available. In the coming weeks this organization will not be able to ingest any new replays. Notify your organization owner to keep using Session Replay." and I have no idea what it means. Do we have to upgrade to business plan to use the feature? Something else? The documentation does not mention anything like "you have to be on business plan to use session replay".

### Suggested Solution

Document this or clarify the message.

**Comment by jas-kas** [comment]
Hi @AlexanderBartash,

Thanks for reaching out re: this banner message and for your feedback.

Session Replay will only be available on a new plan type (this plan type also includes [Dynamic Sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/)). Since your organization used Session Replay during our beta period, you will be able to continue to use Session Replay for 2 more billing cycles at no cost and without updating your plan. However, after the 2 billing cycles period (i.e., 'in the coming weeks'), your organization owner must update your plan to continue to use Session Replay as replays will no longer be ingested. If your organization owner updates your plan and the 2 billing cycles period has passed, you will have 500 replays/mo included for free on the Team plan. More pricing details found [here](https://docs.sentry.io/product/accounts/pricing/#per-category-pricing).

This is **not** related to upgrading to Business. There _may_ be pricing implications in some cases as a result of updating your plan type and that will be communicated to the organization owner. 

We'll work to update this messaging based on your feedback and others we receive from customers. Let me know if you have any questions.
