### ISSUE TITLE
List Your Organizations API endpoint documentation clarification

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry-docs#6443]
### Core or SDK?

Core Sentry product

### Which part? Which one?

API

### Description

A customer was confused with the [List Your Organizations](https://docs.sentry.io/api/organizations/list-your-organizations/) documentation as there is no mention that the auth token needed is a user auth token. The customer was utilizing an internal integration token.

### Suggested Solution

Explicitly mention this only works with user API tokens and not developer integration API tokens.

**Comment by shanamatthews** [comment]
Due to the way these pages are generated, it's quite hard to customize the "Scopes" section on these endpoint pages. What we can do is add information on the linked [auth page](https://docs.sentry.io/api/auth) about which endpoints require which types of tokens.

Shana todo:

- [ ] Determine which endpoints require user tokens
- [ ] Add that info to https://docs.sentry.io/api/auth
