### ISSUE TITLE
Session Replay Lazy-loading in Angular

### ISSUE THREAD

**Issue by Vladi-ed** [getsentry/sentry-docs#6477]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Session Replay

### Description

On this page https://docs.sentry.io/platforms/javascript/guides/angular/session-replay/#lazy-loading-replay
under the Lazy-loading Replay section the example can't be applied to the Angular framework or it's now clear how and where to apply it.

### Suggested Solution

Example should be described clearly same way as in [Getting started](https://docs.sentry.io/platforms/javascript/guides/angular/) page.

**Comment by Vladi-ed** [comment]
What I see now is a vanilla JS implementation.

It should be replaces with something like this:

```
import {getCurrentHub, Replay} from '@sentry/angular-ivy';

getCurrentHub()
  .getClient()
  .addIntegration(new Replay());
```

**Comment by AbhiPrasad** [comment]
Yup you're right! PRs are welcome, and backlogging for now.

**Comment by Vladi-ed** [comment]
I've tested the code above and that syntax:
`const { Replay } = await import('@sentry/angular-ivy');`
actually not working as lazy loading and loads all the library in the main bundle..

In order to make it work as a lazy loading you should import it like that in a lazy loaded Angular component:
`import {getCurrentHub, Replay} from '@sentry/angular-ivy';`

And than use it inside a component:
```
      getCurrentHub()
        .getClient()
        .addIntegration(new Replay());
```

**Comment by AbhiPrasad** [comment]
Interesting, seems like something specific to angular lazy loading? I wonder if there is a way to lazy load outside of a component - but not too familiar with angular internals to know.

Again, we just need to update the snippet!

**Comment by Lms24** [comment]
@Vladi-ed just to clarify: With "lazy-loaded Angular component", do you mean a component that's declared in a lazy loaded NgModule? That would make sense to me. Interesting though that `await import` doesn't seem to work in Angular. Haven't heard that before.

**Comment by Vladi-ed** [comment]
@Lms24 

> component declared in a lazy loaded NgModule

Yes, that's what I've tested. Although the Angular team has added Standalone Components recently that can be lazy-loaded same way as Modules.

> await import

It works but not as expected. That's why I thing the code example I see in the sentry docs is a bit confusing.

**Comment by Vladi-ed** [comment]
> it is bundled into the main js file in prod builds

correct, but I didn't test when it actually starts the recording in this case.

> Would you mind telling us how you are going to use Replay?

Sure, my angular application is used by random people in the internet and it can take more than 20 seconds to load the app on slow mobile connection. So when I watch Replay I have to watch all the loading time or skip to the next "keyframe". So after lazy loading implementation I start the "record" only when the page is fully loaded. 

And the most important thing is that I was able to reduce main bundle side after making Replay lazy-loaded!

**Comment by vivianyentran** [comment]
@Lms24 Can you take another look at this?

**Comment by Lms24** [comment]
Hi, sorry about this! Unfortunately, I'm super busy with v8. Once we have some breathing room after the release I can take a look. I added it to our immediate backlog.

**Comment by Lms24** [comment]
Hey folks, quick update: I tried a bunch of stuff to get lazy loading working nicely in Angular today but it seems webpack (+ maybe some Angular-internal build weirdness) is really making our/your lives hard here. 

I tested both, lazy loaded standalone components as well as lazy-loaded modules and it seems like as soon as I import `replayIntegration` in the lazy loaded module/component, the initial bundle size increases. This is the case for top level `import {replayIntegration}` as well as for  dynamic `import('@sentry/angular').then(...)`. 

My research so far shows that this seems to be caused by webpack. Seems like webpack has some logic in place that checks if dynamically imported modules were already imported statically before. In case of the Sentry SDK, this is indeed the case, because we instruct you to import the SDK in `main.ts` as well as `app.module.ts`/`app.config.ts`. As a result, webpack pulls in more stuff into the main bundle and imports that from the dynamically imported bundle via a small shim. 

This is really unfortunate because it complicates lazy-loading a lot. But there are two workarounds. I recommend the first one and will add this to the docs in a sec.

### [recommended] Use `lazyLoadIntegration` and Replay CDN bundle

The idea here is that instead of generating the lazy loaded JS chunk yourself during build and dynamic imports, you simply inject our Replay integration CDN bundle and use that. I tested this and it seems to work fairly well. 

In your lazy-loaded component/module:

1. Import the necessary helpers from the SDK: 
   ```ts
   import { addIntegration, lazyLoadIntegration } from '@sentry/angular';
   ```
2. Lazy load and add the integration:
   ```ts 
   ngOnInit() {
    lazyLoadIntegration('replayIntegration').then((replayIntegration) => {
      addIntegration(replayIntegration());
    });
   }
   ```
 
Remember to still set `replaysSessionSampleRate` and `replaysOnErrorSampleRate` in your `Sentry.init` call!

### [not recommended] Workaround 2: Always import `@sentry/angular` dynamically 

I tested this as far as building and quickly serving the application locally. We don't recommend this approach because it will init the SDK later than the Angular SDK bootstrapping, meaning early errors might not be caught. 

1. In `main.ts` replace the static import with a dynamic one:
   ```ts
   import("@sentry/angular").then(Sentry => Sentry.init(...))
   ```
2. In `app.config.ts` do the same thing and push the providers to the config object
   ```ts
   import('@sentry/angular').then((Sentry) => {
     appConfig.providers.push([
       {
         provide: ErrorHandler,
         useValue: Sentry.createErrorHandler(),
       },
       {
         provide: Sentry.TraceService,
         deps: [Router],
       },
       {
         provide: APP_INITIALIZER,
         useFactory: () => () => {},
         deps: [Sentry.TraceService],
         multi: true,
       },
    ]);
   });
   ```
3. Finally, in your lazy-loaded component, do the same thing:
   ```ts
   import("@sentry/angular").then(Sentry => Sentry.addIntegration(Sentry.replayIntegration()))
   ```
