### ISSUE TITLE
Missing info about sourcemaps explain command  in Troubleshooting Source Maps

### ISSUE THREAD

**Issue by slestang** [getsentry/sentry-docs#6573]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Sentry-cli

### Description

The first paragraph of the page [Troubleshooting Source Maps](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/) explain that there is a `sentry-cli sourcemaps explain` command to help us debug our sourcemaps. Excellent, but when trying the command, several things are missing:

```
$ sentry-cli.exe sourcemaps explain 836b6b53b84e4c19973de8f3f80c3481
error: An organization slug is required (provide with --org)
```

Ok, I'll add my org:
```
$ sentry-cli.exe sourcemaps explain 836b6b53b84e4c19973de8f3f80c3481 --org XXX
error: A project slug is required
```

Ok, I'll add my project slug, but where to find it ? I try with the project id:
```
sentry-cli.exe sourcemaps explain 836b6b53b84e4c19973de8f3f80c3481 --org XXX --project 4504758654****
error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
```

Hum, ok, let's try with the project name:
```
sentry-cli.exe sourcemaps explain 836b6b53b84e4c19973de8f3f80c3481 --org XXX --project YYY-frontend
error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
```

So I have no idea if my project slug is wrong, or my Sentry CLI token doesn't have enough permissions (they are `org:read, project:releases`)

### Suggested Solution

Please provide all parameters in the documentation example and the way to get the project slug.
Please also provide the permissions required to execute this command.

Maybe the result of the command should specify if it is a permission issue on this specific project/org, or if the token doesn't have the right scopes.

**Comment by slestang** [comment]
I finally re-try with another token with a much wider scope (`event:admin, event:read, member:read, org:read, project:read, project:releases, team:read, event:write, project:write, org:write, org:integrations`) and it works.

**Comment by Lms24** [comment]
Hi @slestang thanks for writing in!

I generally understand that from just looking at the linked "Troubleshooting Source Maps" page, it might appear confusing which parameters are missing or why you got this permissions error. However, the second paragraph links to the [installation and configuration guide](https://docs.sentry.io/product/cli/) of the Sentry CLI, where everything is explained. 

I realize this link is easy to miss so we could probably make it more prominent. Is this what you'd expect from this page?

I'd just argue that we cannot easily put everything necessary into this page because there are different ways how to set up and use the CLI. For instance, you don't have to specify the org and project slug every time. You can also put it into a `.sentryclirc` file, as described [here](https://docs.sentry.io/product/cli/configuration/#configuration-file).

**Comment by slestang** [comment]
Hi @Lms24,

Thanks for the explanations. I understood why you don't want to add the organization and project parameters in the doc, as they can be configured other ways, and the output of the CLI is sufficient to understood how to fix that.

I nevertheless think that the documentation should specify with scopes are required for this specific actions.
It could even be better if the endpoint called by the CLI will respond with something like:

`You do not have permission to perform this action. Required scopes: event:admin, *** (http status: 403)`

If you think the documentation is fine like that, you can close this ticket.

**Comment by Lms24** [comment]
Thanks for getting back to me. I couldn't find the necessary scopes myself in a quick search so I think we should improve the documentation around this,

Tagging @kamilogorek, do you think we should adjust the suggested scopes [here](https://docs.sentry.io/product/cli/configuration/)? Or otherwise [here](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/)?

**Comment by kamilogorek** [comment]
I'd add the note regarding scope requirement to the troubleshooting page.

**Comment by szokeasaurusrex** [comment]
The `sourcemaps explain` command is deprecated. We should replace the documentation of `sourcemaps explain` with the debugger modal documentation that will be added when #9638 is implemented.
