### ISSUE TITLE
Miss information on how AI Suggested Solution use customer data

### ISSUE THREAD

**Issue by kQqhWdGMAS6K4fkw** [getsentry/sentry-docs#6886]
### Core or SDK?

Core Sentry product

### Which part? Which one?

AI Suggested Solution

### Description

Learned that our organization has something call AI Suggested Solutions turned on in Settings. Is it on by default?

Anyhow, as I understand our event data is then sent to OpenAI. But when reading the [documentation](https://docs.sentry.io/product/issues/issue-details/ai-suggested-solution/) I miss information on how OpenAI exactly use our data. This makes it very hard to do a security assessment.

### Suggested Solution

Please add information about this to the documentation.

**Comment by priscilawebdev** [comment]
Thanks, @kQqhWdGMAS6K4fkw  for reaching out. I have added this issue to our backlog and will soon come back to you 😉

**Comment by matejminar** [comment]
The feature or (UI banner) is enabled by default. In order to actually use it, you need to sign explicit consent after clicking on `View Suggestions` (you need to be an org admin in order to do it).

If you don't want anyone in your org to be using the feature because of security concerns. You can disable it in the settings you mentioned and the whole UI banner will disappear.

To learn more about `OpenAI Subprocessor Acknowledgment`, visit Legal&Compliance in Settings.

Does that help?

**Comment by matejminar** [comment]
Relates to https://github.com/getsentry/sentry-docs/issues/6886. Armin will follow-up there with a bit more details.
