### ISSUE TITLE
Why does distributed tracing enforce profiling?

### ISSUE THREAD

**Issue by oliversalzburg** [getsentry/sentry-docs#7409]
### Core or SDK?

Platform/SDK

### Which part? Which one?

AWS Lambda

### Description

[The documentation states](https://docs.sentry.io/platforms/node/usage/distributed-tracing/) that I require performance monitoring to be enabled to make use of distributed tracing at all. Why?

To me as a consumer the connection between these two aspects are entirely unclear. Also, trying to integrate profiling into AWS Lambda was an absolute mess. So _requiring_ this to be able to connect frontend and backend traces seems counter-intuitive.

Or maybe I'm misunderstanding?

### Suggested Solution

I have none.

**Comment by AbhiPrasad** [comment]
Hey @oliversalzburg, thanks for writing in.

Performance monitoring generates spans, which is what distributed tracing uses to establish parent child relationships between different services (span on X service -> span on Y service).

We recognize that this is not always ideal though. In the next release of the Node SDK (so serverless as well), we'll be releasing support for tracing without performance, which allows you to do distributed tracing without turning on performance monitoring. Please follow along progress on that here: https://github.com/getsentry/sentry-javascript/issues/8352

**Comment by AbhiPrasad** [comment]
> Also, trying to integrate profiling into AWS Lambda was an absolute mess

Could you elaborate on why this was difficult for you? Was there something in https://docs.sentry.io/platforms/node/guides/aws-lambda/performance/instrumentation/automatic-instrumentation that did not work?

**Comment by mjq-sentry** [comment]
Hi @oliversalzburg! I just wanted to clarify a couple of things.

First, this might just be a terminology thing, but distributed tracing doesn't require [Profilling](https://docs.sentry.io/product/profiling/), but it does require [performance monitoring](https://docs.sentry.io/platforms/node/performance/) since that's what actually creates the traces being distributed.

Or at least, it used to! But there's been some work recently to have existing traces propagate properly even if intermediate steps don't have performance monitoring enabled. See for example [the release notes for v7.58.0 of our Javascript SDK](https://github.com/getsentry/sentry-javascript/releases/tag/7.58.0). I believe it is also available in Python and Java. 

@AbhiPrasad, since I saw you worked on that feature - would it be appropriate to update [the Distributed Tracing docs](https://docs.sentry.io/platforms/node/usage/distributed-tracing/) to mention that performance monitoring is no longer required for some SDKs?

**Comment by AbhiPrasad** [comment]
> @AbhiPrasad, since I saw you worked on that feature - would it be appropriate to update [the Distributed Tracing docs](https://docs.sentry.io/platforms/node/usage/distributed-tracing/) to mention that performance monitoring is no longer required for some SDKs?

Docs updates are on the way!

In [Python](https://docs.sentry.io/platforms/python/usage/distributed-tracing/#how-to-use-distributed-tracing) and PHP (SDKs that support tracing without performance), we've already updated the docs.

**Comment by oliversalzburg** [comment]
Of course, you guys are right. Sorry for my confusion, and thanks for all the explanation. Funny enough that I read the release notes earlier today and was like "You got to be kidding me!" 😂

Now back to finding out why the frontend and backend traces are _actually_ not connected in the Sentry UI...
