### ISSUE TITLE
Feedback report: "@sentry/angular-ivy hint in beforeSend doesn't include originalError"

### ISSUE THREAD

**Issue by shanamatthews** [getsentry/sentry-docs#8128]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Angular SDK

### Description

https://docs.sentry.io/platforms/javascript/guides/angular/configuration/filtering/

@sentry/angular-ivy
hint in beforeSend doesn't include originalError

### Suggested Solution

Verify that the passed `hint` does contain `originalExeption` in the angular-ivy SDK. If not, update docs.

**Comment by Lms24** [comment]
I think I'm missing a lot of the original context here but what I can tell is that `originalException` is a property on the event hint that may or may not be defined, as declared in the `EventHint` type:

https://github.com/getsentry/sentry-javascript/blob/8879fd544aba8ed456360ed81d88f82f610d93d9/packages/types/src/event.ts#L84

Therefore, I don't think there's a bug per sé in the docs or the SDK if this property is not present. If the original reporter (I reckon this issue was created from user feedback) is still following this issue by chance, could you share a bit more context?

Otherwise I think we can close this issue for now.
