### ISSUE TITLE
in-app-include doesn't appear to be available for C#

### ISSUE THREAD

**Issue by eddykavanagh** [getsentry/sentry-docs#815]
I'm trying to make use of `in-app-include` in our C# applications, however despite the docs saying it is supported (https://docs.sentry.io/error-reporting/configuration/?platform=csharp#in-app-include) I couldn't find it, only `in-app-exclude` (https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry/SentryOptions.cs#L66)

Is this an error in the docs or is it something I'm doing wrong on the C# side?

**Comment by bruno-garcia** [comment]
@eddykavanagh You are right there's an issue with the docs. That should be marked as no available in C#.

In C#, by default everything is `InApp` except `System.*`, `Microsoft.*` and other common namespaces.
So far the most use cases that showed up are to exclude some third party libraries but not to mark your own `System.MyThing` as include (because that'd be excluded by default).
Are in need of `InAppInclude`? Could you please describe your use case?

**Comment by eddykavanagh** [comment]
OK no worries, good to know we're not missing something.

So all our code lives in `CompanyName.*` namespaces. We're centralising our base configuration to be able to apply it to all projects, so rather than `InAppExclude` the complete superset of all third party libraries we use across every project, it seemed more natural to just `InAppInclude` our company namespace.
