### ISSUE TITLE
Documentation on showReportDialog showing for Android SDK when it is not available.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-docs#8815]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/android/user-feedback/configuration/

### Description

The page above shows options on how to configure Sentry.showReportDialog in the Android SDK, leading people to conclude this option is available when it is not.

### Suggested Solution

Hide the page for Android SDK.

**Comment by kahest** [comment]
Likely culprit: https://github.com/getsentry/sentry-docs/pull/8714 

I believe this issue is relevant for all platforms listed under `notSupported` [here](https://github.com/getsentry/sentry-docs/pull/8714/files#diff-96770b55eed220e91736b5ea5fe0ef5f2179746ae7fdff316320a937eb7cb4ebL109): `"android", "apple", "java", "native", "dart", "flutter", "ruby", "unity", "react-native", "unreal", "kotlin-multiplatform"`

This change likely also produced https://docs.sentry.io/platforms/native/user-feedback

cc @stephanie-anderson
