### ISSUE TITLE
Search functionality for "search all sites" not working

### ISSUE THREAD

**Issue by lizokm** [getsentry/sentry-docs#9034]
### Steps to Reproduce

1. Go to docs homepage: https://docs.sentry.io/
2. Search for something (ie. attachements, python, images)
3. There's a link at the bottom of the search results that says: "Search for {whatever you searched for} across all Sentry sites}
![Screenshot 2024-02-01 at 4 29 06 PM](https://github.com/getsentry/sentry-docs/assets/26800704/c205dfd7-9cba-45fc-9e1d-897504287cfd)

### Expected Result

Ability to click on link and get results

### Actual Result

Nothing happens

**Comment by Shubhdeep12** [comment]
It is working but I think there are 2 issues with UX

1. This issue is with dev docs as well - https://develop.sentry.dev/   this button indicates that user has to click on it but actually on hovering over this button, the results from other deocs also adds.
2. here on sentry docs after hovering -> the other results gets added -> but button is not removing. it is removing from dev docs but not from here
3.
