### ISSUE TITLE
CORB issue when clicking on search suggestion which links to the same page as you are currently on

### ISSUE THREAD

**Issue by s1gr1d** [getsentry/sentry-docs#9315]
### Steps to Reproduce

1. Go to e.g. https://docs.sentry.io/platforms/javascript/install/loader/ 
2. Search for "CDN"
3. Click on a suggestion that will link to the same page (JavaScript > Install > Loader)

### Expected Result

The search suggestion pop-up closes and the content scrolls to the search result

### Actual Result

When clicking on the suggestion, nothing happens and Chrome shows a CORB issue in the "issues" tab

![image](https://github.com/getsentry/sentry-docs/assets/32902192/ac42907f-d76e-4366-a691-cc6fdffe5001)

**Comment by Shubhdeep12** [comment]
Hi @s1gr1d 
Two things happening here redirecting to the URL of search results &  tracking search results clicks.

1. Looks like for search results mapping, we only redirect the user to the corresponding page, which automatically closes the search bar, and in this case, the URL is the same. (ideally on clicking it should close the search results and scroll down to the first match)
2. The API to track the search click events on the Algolia side is getting a CORB issue, not sure if it is intended because we do not depend on the response of this API.

Any thoughts here @stephanie-anderson @mjq-sentry

**Comment by a-hariti** [comment]
The CORB warning is not interfering with anything. It's a side effect of the implementation details of Algolia using [navigator.sendBeacon()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)

You can read more [here](https://support.algolia.com/hc/en-us/articles/4418789171601-I-am-seeing-a-Cross-Origin-Read-Blocking-error-CORB-error-in-the-console-when-using-Google-Chrome-what-does-this-mean)
