### ISSUE TITLE
[Bug - Changelog] Categories Filter Does Not Work as Expected

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry-docs#9414]
## Bug Report

When I select the "Replay" category, I see a single changelog entry from April 2023 titled "User Click Search for Session Replay". However, it's apparent from the main list view that there are many other changelog entries with the "Replay" category but they fail to show up. See screen recording. 

https://github.com/getsentry/sentry-docs/assets/77064737/0473f8ba-e0d6-49b5-b12e-fce98cd5227f

**Comment by Shubhdeep12** [comment]
Yes, it's not working. There can be some issue in the categories array of a post because only the posts with title matching the selected categories are filtering out.

Can we add a migration file or something to add some dummy data or some posts that will help debugging the issues in changelog locally.
