### ISSUE TITLE
Performance Monitoring in Android available from?

### ISSUE THREAD

**Issue by rungta-naman** [getsentry/sentry-docs#9623]
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android

### Description

I have been upgrading Android SDK and had a difficult time finding out from which version of SDK performance monitoring works and I am still unsure as it doesn't show in the performance section of the doc.

### Suggested Solution

Please show the availability of the feature version wise.

**Comment by kahest** [comment]
Performance is supported in sentry-java since version 4.0.0 which was released in Jan 2021. However, specific integrations or features might require newer versions, which we generally try to point out.
There are plans to add this version/support information in a generic way by plugging into a central registry of releases, so I will close this issue for now.
