### ISSUE TITLE
Document policy violation: js-profiling is not allowed in this document in reactjs application

### ISSUE THREAD

**Issue by e-kibet** [getsentry/sentry-docs#9714]
### Steps to Reproduce

1. Create the reactjs application
2. Create the project on the sentry dashboard and configure the project including the profiling
3. Set the document policy on the backend i.e. if you are using expresjs you can set as 
app.use((_req, res, next) => {
  res.set("Document-Policy", "js-profiling");
  next();
});

4. reload the project to see if the profiling has been set up on the sentry -> project-> profiling section, then check the browser console.

### Expected Result

- With the clear instructions on the https://docs.sentry.io/platforms/javascript/guides/react/profiling/ i would expect the profiling to work on reactjs project

### Actual Result

Document policy violation: js-profiling is not allowed in this document in reactjs application

**Comment by lizokm** [comment]
@AbhiPrasad would really appreciate it if you could take a look.

**Comment by AbhiPrasad** [comment]
Hey @e-kibet thanks for writing up an issue!

This error occurs because the `js-profiling` document policy was not set properly. Could you check your chrome dev tools and make sure the header is being set properly? 

<img width="475" alt="image" src="https://github.com/getsentry/sentry-docs/assets/18689448/25c756e6-4377-42d8-ad32-b0db4a922538">
