### ISSUE TITLE
Sentry CORS issue page is showing up as an error

### ISSUE THREAD

**Issue by lizokm** [getsentry/sentry-docs#9876]
### Steps to Reproduce

Search for: Sentry CORS 

https://docs.sentry.io/platforms/ruby/guides/sidekiq/usage/distributed-tracing/dealing-with-cors-issues/
![Screenshot 2024-04-30 at 1 23 31 PM](https://github.com/getsentry/sentry-docs/assets/26800704/ec6401ec-6ee5-4409-8f54-7fa0bfa7fba2)

### Expected Result

See the page

### Actual Result

404 error

**Comment by Shubhdeep12** [comment]
yeah looks like Algolia is returning outdated URLs

**Comment by a-hariti** [comment]
@Shubhdeep12 +1

This is probably an Algolia index out of date issue, otherwise it's a missing redirect from somewhere, which would warrant further investigation for similar urls

the actual page for this link is [here](https://docs.sentry.io/platforms/ruby/guides/sidekiq/distributed-tracing/dealing-with-cors-issues/)

@lizokm
